### ISSUE TITLE
"Raw" filter returns string

### ISSUE THREAD

**Issue by SharkyKZ** [joomla-framework/filter#38]
### Steps to reproduce the issue

    var_dump((new Joomla\Filter\InputFilter)->clean(1, 'raw'));

### Expected result

    int 1

### Actual result

    string '1'

### Additional comments

Since https://github.com/joomla-framework/filter/commit/e4d3d158eabae41edfdbfea482a2b5feae71a187.

**Comment by nibra** [comment]
Fixed in `master`. Thank you!
