### ISSUE TITLE
Saving Global Configuration broken in the 4.0-dev branch of the CMS when updating joomla/filter from 2.0.0-beta2 to 2.0.0-beta3 or 2.0.0-beta4 

### ISSUE THREAD

**Issue by richard67** [joomla-framework/filter#41]
### Steps to reproduce the issue

It seems that beginning with version 2.0.0-beta3, the filter package breaks saving Global Configuration in the 4.0-dev branch of the CMS, see https://github.com/joomla/joomla-cms/pull/32207#issuecomment-770240778 .

I.e. update the filter package on J4 to version 2.0.0-beta3 or 2.0.0-beta4. Then go to Global Configuration and try to save.

### Expected result

Works.

### Actual result

```
PHP Recoverable fatal error:  Object of class stdClass could not be converted to string
in /home/richard/lamp/public_html/joomla-cms-4.0-dev/libraries/vendor/joomla/filter/src/InputFilter.php on line 239,
referer: https://www.joomla-40-dev.vmkubu02.vmnet2.local/administrator/index.php?option=com_config
```

**Comment by nibra** [comment]
The source to be cleaned must be a string, not an object.

**Comment by richard67** [comment]
So it's an error in the CMS? But why does it then happen with the filter package versions 2.0.0-beta3 and 2.0.0-beta4 but not with 2.0.0-beta2?

**Comment by nibra** [comment]
Because the type safety was increased

**Comment by richard67** [comment]
So shall I close this issue here?

**Comment by nibra** [comment]
Maybe we should wait for other view-angles. Let it stay open for 24hrs. If nothing happens within that time frame, we can safely close this.

**Comment by richard67** [comment]
I've debugged a bit and found out that when `$source` is an object so the error happens, the `$type` parameter is empty, i.e. it does not use the default `'string'`like it would be if that parameter was missing, and so `$method` is set to `'clean'`, i.e. the clean function calls itself again recursive.

And when I encode that object to a json string, I get:

```
{"1":{"filter_type":"NH","filter_tags":"","filter_attributes":""},"9":{"filter_type":"NH","filter_tags":"","filter_attributes":""},"6":{"filter_type":"BL","filter_tags":"","filter_attributes":""},"7":{"filter_type":"BL","filter_tags":"","filter_attributes":""},"2":{"filter_type":"NH","filter_tags":"","filter_attributes":""},"3":{"filter_type":"BL","filter_tags":"","filter_attributes":""},"4":{"filter_type":"BL","filter_tags":"","filter_attributes":""},"5":{"filter_type":"BL","filter_tags":"","filter_attributes":""},"8":{"filter_type":"NONE","filter_tags":"","filter_attributes":""}}
```
Maybe that helps to find out what goes wrong.

To me it seems that the refactoring of the input filter released with 2.0.0-beta3 has some mistake somewhere.

**Comment by richard67** [comment]
The problem is caused here:

https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Form/FormField.php#L1171

When debugging, I saw it calls the `InputFilter::getInstance()->clean` function with parameter `$filter` being an empty string and not null, and so the default value `'string'` for that parameter is not used.

The easiest way to fix it is to add 1 code line to the top of the input filter's `clean` function like this:

`$source ?: 'string';`

What do you think?

**Comment by richard67** [comment]
Hmm, but that doesn't help with the problem.

**Comment by richard67** [comment]
It happens with a form which has name (`$this->name`) = 'jform[filters]'.

**Comment by nibra** [comment]
If the `filter` argument is an empty string, the `clean()` method calls itself without `filter` argument, leading to `filter='string'`, which should be fine. The problem is the `source` to be filtered not being a string. The `InputFilter` has no knowledge about the object, so it couldn't filter it even if objects were allowed.

**Comment by richard67** [comment]
@nibra If I change in the InputFilter in function clean toe following code

```
		if (\is_array($source))
		{
			$result = [];

			foreach ($source as $key => $value)
			{
				$result[$key] = $this->clean($value, $type);
			}

			return $result;
		}
```

as folows

```
		if (\is_object($source) || \is_array($source))
		{
			$result = [];

			foreach ((array) $source as $key => $value)
			{
				$result[$key] = $this->clean($value, $type);
			}

			return $result;
		}
```

then it works.

Not sure if it's the right solution, but maybe it helps.

**Comment by richard67** [comment]
@nibra When I've compared beta2 with beta3 where the refactoring was made, I saw that before the refactoring in some cases (filter types) not the value was typecasted to string but the result of the regex functions, e.g. for type 'WORD': `$result = (string) preg_replace($pattern, '', $source);`.

Refactoring changed that to always cast the value before the call.

In addition it seems that in J4 validation has been added for certain kinds of fields which was not there in J3, so that might be a reason why the problem doesn't happen with the refactored master code on J3.

**Comment by richard67** [comment]
So I think the above suggestion (together with change of the parameter doc block) would be a valid fix.

**Comment by nibra** [comment]
That would lead to an object being filtered into an array. That's quite counter-intuitive. So, if objects need to be covered, they need 'their own section'.

Then how should objects be treated in general? Should only public members be filtered? Should filtering be rejected, if the object contains non-public members? Should we use `Reflection` to determine the right type of the object's members?

This is why objects are excluded from filtering. I don't see a solution general enough to be included in a library package.

In the current situation, the solution is to eventually cast the source to an array in the calling code; thus the conversion object->array is documented where it is needed.

**Comment by richard67** [comment]
Yes, agree meanwhile. Not sure if I can solve it.

**Comment by richard67** [comment]
See https://github.com/joomla/joomla-cms/pull/32207#issuecomment-770387471 ... Let's hope we get some help there.

**Comment by richard67** [comment]
Closing as not a filter issue. See comments in https://github.com/joomla/joomla-cms/pull/32207 for details.
